apiVersion: v1
kind: Pod
metadata:
  name: group-2-ubuntu-volume
spec:
  containers:
  - name: group-2-ubuntu-volume
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: nfs-cc-group2
      mountPath: /test-data
  volumes:
  - name: nfs-cc-group2
    persistentVolumeClaim:
      claimName: nfs-cc-group2
